#!/bin/sh - 

set -e
basedir=$(dirname $(dirname $0))

[ -z "$TMPDIR" ] && TMPDIR=/tmp

files=
dest=
time=
leaveasm=
splitasm=
verbose=
compiler=$basedir/build/stage2
runtimedir=$basedir/runtime

while [ $# -gt 0 ] ; do
    case $1 in 
    -o)
        dest="$2"
        shift 2
        ;;

    -T)
        time=1
        shift 1
        ;;
        
    -D)
        runtimedir="$2/runtime"
        compiler="$2/build/stage2"
        shift 2
        ;;

    -C)
        compiler="$2"
        echo "$compiler" | grep '/' >/dev/null || compiler="./$compiler"
        shift 2
        ;;
    
    -s)
        leaveasm=1
        shift 1
        ;;

    -S)
        splitasm=1
        shift 1
        ;;

    -v)
        verbose=1
        shift 1
        ;;

    -*)
        echo "Unknown option $1" 1>&2
        exit 1
        ;;

    *)
        files="$files $1"
        shift 1
        ;;
    esac
done

cmd="$compiler compile $runtimedir/runtime.pco $runtimedir/runtime2.pco $runtimedir/gc.pco $files"

[ -n "$verbose" ] && echo $cmd 1>&2

if [ -n "$time" ] ; then
    $(which time) -f "%E" $cmd >/dev/null
else
    if [ -z "$dest" ] ; then
        echo "Destination file not specified" 1>&2
        exit 1
    fi

    asmclean=''
    if [ -z "$leaveasm" ] ; then
        asmdest=$TMPDIR/$$
        trap 'rm -rf $asmclean' EXIT
    else
        asmdest=${dest}
    fi

    asmout="${asmdest}.s"
    asmclean="$asmout"
    asmfiles="$asmout"
    eval $cmd >"$asmout"

    if [ -n "$splitasm" ] ; then
        asmdir="${asmdest}-asm"
        mkdir $asmdir
        asmclean="$asmout $asmdir"
        asmfiles=`awk -v dir=$asmdir 'BEGIN { l = 0; fnum = 0; fn=dir "/0.s"; print fn; } /^# BREAK$/ { if (l > 10000) { l = 0; fnum++; fn=dir "/" fnum ".s"; print fn; next; } } { l++; print $0 >fn; }' $asmout`
    fi
    
    target=''
    # bit of a hack: if we are on x86-86, but it looks like the compiler
    # didn't produce x86-64 asm, assume a i386 target
    if [ "$(uname -m)" = x86_64 ] && ! grep -m1 '^movq' $asmout >/dev/null ; then
        target='-m32'
    fi
    
    gcc -Wall -g $target $asmfiles $runtimedir/main.c -o $dest
fi
