#!/bin/sh - 

set -e
cdir=$(readlink -f "$(dirname $0)/..")

[ -z "$TMPDIR" ] && TMPDIR=/tmp

files=
dest=
time=
leaveasm=
compiler=$cdir/stage2

while [ $# -gt 0 ] ; do
    case $1 in 
    -o)
        dest="$2"
        shift 2
        ;;

    -T)
        time=1
        shift 1
        ;;
        
    -D)
        cdir="$2"
        compiler=$cdir/stage2
        shift 2
        ;;

    -C)
        compiler="$2"
        echo "$compiler" | grep '/' >/dev/null || compiler="./$compiler"
        shift 2
        ;;
    
    -s)
        leaveasm=1
        shift 1
        ;;

    -*)
        echo "Unknown option $1" 1>&2
        exit 1
        ;;

    *)
        files="$files $1"
        shift 1
        ;;
    esac
done

cmd="$compiler compile $cdir/runtime.lisp $cdir/runtime2.lisp $cdir/gc.lisp $files"

if [ -n "$time" ] ; then
    $(which time) -f "%E" $cmd >/dev/null
else
    if [ -z "$dest" ] ; then
        echo "Destination file not specified" 1>&2
        exit 1
    fi

    if [ -z "$leaveasm" ] ; then
        asmout=$TMPDIR/$$.s
        trap 'rm -f $asmout' EXIT
    else
        asmout=${dest}.s
    fi

    eval $cmd >$asmout
        
    target=''
    # bit of a hack: if we are on x86-86, but it looks like the compiler
    # didn't produce x86-64 asm, assume a i386 target
    if [ "$(uname -m)" = x86_64 ] && ! grep -m1 '^movq' $asmout >/dev/null ; then
        target='-m32'
    fi
        
    gcc -Wall -g $target $asmout $cdir/main.c -o $dest
fi
