#!/bin/sh -

command="--noinform --noprint"
for f in $CL_COMPILER_SOURCES ; do
  command="$command --load $f"
done

func=$1
shift

string_list () {
    l=""
    for f in $* ; do
        l="$l \"$f\""
    done
    echo $l
}

case $func in
interpret)
    form="(do-interpret-files '($(string_list $*)) '(runtime-main))"
    ;;
compile)
    form="(do-compile-files '($(string_list $*)) '(runtime-main))"
    ;;
expand)
    form="(do-expand-files '($(string_list $*)))"
    ;;
dump)
    phase=$1
    shift
    form="(do-dump-program \"$phase\" '($(string_list $*)) '(runtime-main))"
    ;;
*)
    echo "unknown command $1" 1>&2
    exit 1
esac

sbcl $command --eval "(progn $form (quit))"
